### PR TITLE
SQL: report an error when the user used a wrong keyword

### PR DESCRIPTION
**Pull request by briot**
In a database schema description, tables should start with TABLE,
 ABSTRACT TABLE or VIEW. Report an error in other cases

### CODE REVIEW

**Comment by briot** [comment]
The reason we have a Schema_Type is so that we can have a different name (for instance "my_date") in a schema description file (.txt) than in the database itself (where it would likely be mapped to "date"). The goal is that I can represent dates or other types differently in Ada, but still map them to the same underlying type in the database.
This was already doable before by overriding subprograms directly, but having it as a formal parameter for the generic makes it slightly more convenient

**Comment by anisimkov** [comment]
On 2017-04-26 15:18, Emmanuel Briot wrote:
> The reason we have a Schema_Type is so that we can have a different name
> (for instance "my_date") in a schema description file (.txt) than in the
> database itself (where it would likely be mapped to "date"). The goal is
> that I can represent dates or other types differently in Ada, but still
> map them to the same underlying type in the database.

Do you mean that this type going to be represented by that name in
gnatcoll_db2ada generated Ada files ?

**Comment by briot** [comment]
"name in the generated file" => exactly
"removing testsuite" => which specific commit, that was not an intentional change if that's the case.

**Comment by anisimkov** [comment]
On 2017-04-26 16:21, Emmanuel Briot wrote:
> "name in the generated file" => exactly
How the generated file going to see the user defined type ?
Is there going to be subtype generation ?

> "removing testsuite" => which specific commit, that was not an
> intentional change if that's the case.
https://github.com/AdaCore/gnatcoll/pull/6/files/42300e1fbc8be04652a8c2fa240732a0c51f2369

**Comment by briot** [comment]
The generated file doesn't see it (my fault, confusion in my explanation). The use is for people who maintain the .txt itself to generate the DB API (*ads). Then the Ada files will use the proper type, as well as the database if they decide to create a database from the schema as well. The schema is the master, here.

For the testsuite: indeed, the patch picked up a local change I had before I left. The testsuite cannot be run by most users otherwise, since it assumes it can connect to a local postgreSQL server. We argued before, and I think the right approach is for the test to have a @can_run_postgres decorator or some such (which possibly could be set after you tried running "psql" in __init__.py)

**Comment by anisimkov** [comment]
I was a bit confused. It is because I was talking about old commits. I'm
trying to understand how to accept the subj one in github.

**Pull request closed without merging**
