### PR TITLE
Wip/sql improvements

### PR DESCRIPTION
**Pull request by briot**
The same pull request I had before, but done on a separate branch so that I can have multiple such branches and still keep up.
There is a significant number of patches, all involving GNATCOLL.SQL.*

### CODE REVIEW

**Comment by briot** [comment]
Absolutely (I actually had the case on my machine). One simple example is that psql is not the PATH, even though it might be installed on the machine. Another case is when the user has only installed the server packages for postgres (along with include files), but not the client part.

**Comment by briot** [comment]
You might want to close this pull request and comment on the other one. It includes the same patches, and is up-to-date with regards to your version of GNATCOLL. Sorry for the confusion here, I had not realized initially that in github a pull request was actually tracking a branch, not referring to a single commit

**Comment by anisimkov** [comment]
I made the comment under the "SQL: report an error when the user used a wrong keyword" pull request, and I do not see that it is already commited. If you know what is duplicated, close it yourself please. I can detect duplication only on merge.

**Comment by anisimkov** [comment]
The code 
-
-               else
-                  Put_Line (Standard_Error,
-                            Self.File.Display_Full_Name
-                            & ":" & Image (Line_Number, Min_Width => 1)
-                            & " Expecting ""ABSTRACT TABLE"","
-                            & " ""TABLE"" or ""VIEW""");
-                  raise Invalid_File;
was added and then removed in another commit. I'm making rebase. Do we need this code ?

**Comment by briot** [comment]
> 
> was added and then removed in another commit. I'm making rebase. Do we need this code ?

Yes we do. I am not sure why it was removed, likely an wrong manipulation on my part.
It displays an error message when the configuration file is invalid

**Comment by anisimkov** [comment]
Why did you removed the As_Long_Float in SQL.Exec ?

**Comment by briot** [comment]
> Why did you removed the As_Long_Float in SQL.Exec ?

For consistency with other custom types declared in GNATCOLL.SQL_Fields.
There is no As_JSON or As_XML either.

I think it is better to write:

     Long_Float_Fields.As_Param (1.0)
or even
     Integer_Fields.As_Param (1)

That way this is fully consistent for any field type, including those created by
users.

**Comment by briot** [comment]
> 12b0e7c
> file src/gnatcoll_support.c like rollback from previous commit. Looks like you did not take look at your changes. A lot of back modifications.


Actually, I strangely did look at my modifications. Everything in this patch is on purpose.
If you look at the commit message, it explains there was code duplication, which got removed.
Perhaps this is what had you confused ?

**Comment by briot** [comment]
I realize this series of patches is significant and hard to review (that’s also because
it took AdaCore several weeks to get the papers, so patches accumulated).

How about I squash everything into a single commit. That will help review, since code
that was modified (for instance in the testsuite’s __init__.py) was in fact put back and
improved on later on. So you’ll get to see the final result only.

**Comment by anisimkov** [comment]
I prefer one functionality for one patch.
Too big patch is not convenient for review. But if it propose one functionality, it's OK.

**Comment by anisimkov** [comment]
<<Everything in this patch is on purpose.>> the modification of src/gnatcoll_support.c in patch 
12b0e7cb0f03c5c91255b74fae8147f33f79cc3f removing empty gnatcoll_madvise and no any note about it in comment. This empty routine was introduced in anouther commit with appropriate comment.

**Comment by briot** [comment]
> I prefer one functionality for one patch.
> Too big patch is not convenient for review. But if it propose one functionality, it's OK.


But I don’t have the time to go back 30 commits back in time to reorganize things fully the way
you would like it. So basically it will be hard to make progress here.

**Comment by anisimkov** [comment]
Another if we agree that I'll rebase and edit the patches. If you agree I'll ask management.

**Comment by anisimkov** [comment]
MAnu, Close this pull request please, if you know that it is already overwritten.

**Comment by briot** [comment]
All commits are also in #9, so let's take it from there. That pull request is also rebased on the current master, so might be easier to merge

**Comment by briot** [comment]
> Another if we agree that I'll rebase and edit the patches. If you agree I'll ask management.


I certainly have no problem if you edit the patches. I would think it would be easier to squash
everything into a single patch (that’s a lot of lines modified, around 2800, but at least you
are only seeing them once). In particular, your comments about the testsuite become mute
because all the tests now properly emit a “skipped” when they are not run.

I would of course take the time to merge all commit messages into a single one, no problem
to do that.

There are one or two patches related to GNATCOLL.String, which I could keep separate

**Pull request closed without merging**
