### PR TITLE
Cleanups in GNATCOLL.SQL to support custom field types

### PR DESCRIPTION
**Pull request by briot**
This is the same series of patches as in pull request #9, but reorganized and grouped so hopefully they will be easier to validate. The last one is large, but avoids some back and forth in the code (and intermediate commits) that were making the other pull request harder to understand.

### CODE REVIEW

**Comment by anisimkov** [comment]
I used such config

./configure --prefix=/App/gnat --enable-gpl --enable-build=Debug

GNAT Pro 18.0w (20170525-63)

at previous commit 975d13ff9c9af88b7e26654374750dd00831050b

====== Building static tools ======
gprbuild  -p -m -j0 -XLIBRARY_TYPE=static -XGnatcoll_Build=Debug -XXMLADA_BUILD=static -q -Psrc/gnatcoll_tools
gnatcoll_db2ada-generate.adb:128:36: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:215:39: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:530:07: no candidate interpretations match the actuals:
gnatcoll_db2ada-generate.adb:530:07: too many arguments in call to "Write_Schema"
gnatcoll_db2ada-generate.adb:531:13: "Connection" is undefined
gnatcoll_db2ada-generate.adb:531:33: unmatched actual "Puts" in call
gnatcoll_db2ada-generate.adb:546:80: (style) this line is too long

   compilation of gnatcoll_db2ada.adb failed

   
at last one 5a5e63d7ce21f82d444c43131e983a097fb8eec8
   
gnatcoll-sql-ranges.adb:256:01: (style) trailing spaces not permitted
gnatcoll-sql-ranges.ads:260:80: (style) this line is too long
gnatcoll-sql-ranges.ads:263:22: (style) space required

**Comment by anisimkov** [comment]
GNAT Pro wavefront 20170625-63 the same results

**Comment by briot** [comment]
> ====== Building static tools ======
> gprbuild -p -m -j0 -XLIBRARY_TYPE=static -XGnatcoll_Build=Debug -XXMLADA_BUILD=static -q -Psrc/gnatcoll_tools
> gnatcoll_db2ada-generate.adb:128:36: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
> gnatcoll_db2ada-generate.adb:215:39: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
> gnatcoll_db2ada-generate.adb:530:07: no candidate interpretations match the actuals:
> gnatcoll_db2ada-generate.adb:530:07: too many arguments in call to "Write_Schema"
> gnatcoll_db2ada-generate.adb:531:13: "Connection" is undefined
> gnatcoll_db2ada-generate.adb:531:33: unmatched actual "Puts" in call
> gnatcoll_db2ada-generate.adb:546:80: (style) this line is too long
> 
> compilation of gnatcoll_db2ada.adb failed
> 
> at last one 5a5e63d
> 
> gnatcoll-sql-ranges.adb:256:01: (style) trailing spaces not permitted
> gnatcoll-sql-ranges.ads:260:80: (style) this line is too long
> gnatcoll-sql-ranges.ads:263:22: (style) space required


I fixed all the style issues, but I do not see the errors in gnatcoll_db2ada-generate.adb
There is no Get_Actual_Type on line 128 on that branch

**Comment by anisimkov** [comment]
build is OK now.

**Comment by anisimkov** [comment]
make test is not clean on my side.

**Comment by anisimkov** [comment]
by the way, from one of regression

**Comment by anisimkov** [comment]
with GNATCOLL.SQL; use GNATCOLL.SQL;
 pragma Warnings (Off, "no entities of * are referenced");
-with GNATCOLL.SQL_Fields; use GNATCOLL.SQL_Fields;
 pragma Warnings (On, "no entities of * are referenced");
 with DB_Names; use DB_Names;
 package DB is
@@ -17,13 +16,13 @@

        Index    : Integer)
    is abstract new SQL_Table (Ta_Action_Item, Instance, Index) with
    record
-      Id : SQL_Field_Integer (Ta_Action_Item, Instance, N_Id, Index);
-      Date_Done : SQL_Field_Time (Ta_Action_Item, Instance, N_Date_Done, Index);
-      Priority : SQL_Field_Integer (Ta_Action_Item, Instance, N_Priority, Index);
-      Se_Nb : SQL_Field_Integer (Ta_Action_Item, Instance, N_Se_Nb, Index);
-      Status : SQL_Field_Integer (Ta_Action_Item, Instance, N_Status, Index);
-      What_Done : SQL_Field_Text (Ta_Action_Item, Instance, N_What_Done, Index);
-      Who_Done : SQL_Field_Integer (Ta_Action_Item, Instance, N_Who_Done, Index);
+      Id : GNATCOLL.SQL.SQL_Field_Integer (Ta_Action_Item, Instance, N_Id, Index);
+      Date_Done : GNATCOLL.SQL.SQL_Field_Time (Ta_Action_Item, Instance, N_Date_Done, Index);
+      Priority : GNATCOLL.SQL.SQL_Field_Integer (Ta_Action_Item, Instance, N_Priority, Index);
+      Se_Nb : GNATCOLL.SQL.SQL_Field_Integer (Ta_Action_Item, Instance, N_Se_Nb, Index);
+      Status : GNATCOLL.SQL.SQL_Field_Integer (Ta_Action_Item, Instance, N_Status, Index);
+      What_Done : GNATCOLL.SQL.SQL_Field_Text (Ta_Action_Item, Instance, N_What_Done, Index);
+      Who_Done : GNATCOLL.SQL.SQL_Field_Integer (Ta_Action_Item, Instance, N_Who_Done, Index);
    end record;

I saw that GNATCOLL.SQL is use visible but used as prefix with fields types.

**Comment by briot** [comment]
> make test is not clean on my side.

Indeed when in Debug mode with pragma Initialize_Scalars and -gnatVa, an exception
is raised when we manipulate Nan and Infinite float numbers.
Fixed now.
There remains, on my machine, a single failing test for gnatcoll-projects, but that’s unrelated
to this patch (and in fact I think Fedor committed a patch for this yesterday).

**Comment by briot** [comment]
>  Date_Done : GNATCOLL.SQL.SQL_Field_Time (Ta_Action_Item, Instance, N_Date_Done, Index);
> I saw that GNATCOLL.SQL is use visible but used as prefix with fields types.


True, for two reasons:

 - consistency with user-define field types, which will have a fully qualified name
 - compatibility with those standards that recommend fully qualified names in specs.

**Comment by anisimkov** [comment]
test_sql2 output differ

**Comment by briot** [comment]
> test_sql2 output differ

Ah, I needed to recompile my own sqlite3_shell, forgot about that
Fixed

**Comment by anisimkov** [comment]
Infosys has a few regressions like this
-compute (Insert_Message): INSERT INTO message_ids (message_id, tn, "offset", "date") VALUES ($1::text, $2::text, $3::integer, $4::timestamp)
+compute (Insert_Message): INSERT INTO message_ids (message_id, tn, "offset", "date") VALUES ($1::text, $2::text, $3::integer, $4::timestamp with time zone)

The type of date is timestamp withOUT timezone but after this modification it treated as with timezone.

**Comment by briot** [comment]
> Infosys has a few regressions like this
> -compute (Insert_Message): INSERT INTO message_ids (message_id, tn, "offset", "date") VALUES ($1::text, $2::text, $3::integer, $4::timestamp)
> +compute (Insert_Message): INSERT INTO message_ids (message_id, tn, "offset", "date") VALUES ($1::text, $2::text, $3::integer, $4::timestamp with time zone)
> 
> The type of date is timestamp withOUT timezone but after this modification it treated as with timezone.


Right, there always was a confusion in GNATCOLL between the two types of timestamps.
In fact, there should really be a timezone in infosys, otherwise the information is pretty much useless.
I think you should upgrade the schema there.

**Comment by anisimkov** [comment]
looks like the timezone issue fixed with that patch
[timezone-diff.txt](https://github.com/AdaCore/gnatcoll/files/1115454/timezone-diff.txt)

**Comment by briot** [comment]
> looks like the timezone issue fixed with that patch
> timezone-diff.txt


Pretty smart.
I would rename “With_Timezone” to “Timestamp_Attributes"
and “Flag” to “With_Timezone”

But otherwise nice improvement !

**Comment by briot** [comment]
> > looks like the timezone issue fixed with that patch
> > timezone-diff.txt


Perhaps one extra difficulty: ideally, we would want to take the Flag (or With_Timezone
in my proposed renaming) in the function

  Time_To_SQL

Unfortunately, GNATCOLL currently does not pass the With_Timezone (or
Timestamp_Attributes in my renaming) to this function, so that might be an additional
improvement to be made.

In the meantime, I think it is not so important: Time_To_SQL always uses “+00:00”
as the time zone, and postgresql will simply ignore it in a “timestamp without timezone”
field.

sqlite of course has no real types anyway, so it will store the string as given by the
user, and adding the timezone or not will make no change

**Comment by anisimkov** [comment]
I tried merge all commits excluding last one, and heve such error
====== Building static tools ======
gprbuild  -p -m -j0 -XLIBRARY_TYPE=static -XGnatcoll_Build=Debug -XXMLADA_BUILD=static -q -Psrc/gnatcoll_tools
gnatcoll_db2ada-generate.adb:128:36: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:215:39: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:530:07: no candidate interpretations match the actuals:
gnatcoll_db2ada-generate.adb:530:07: too many arguments in call to "Write_Schema"
gnatcoll_db2ada-generate.adb:531:13: "Connection" is undefined
gnatcoll_db2ada-generate.adb:531:33: unmatched actual "Puts" in call
gnatcoll_db2ada-generate.adb:546:80: (style) this line is too long

   compilation of gnatcoll_db2ada.adb failed

Looks like last commit has a fix of the errors in previous commits.

**Comment by briot** [comment]
> Looks like last commit has a fix of the errors in previous commits.

That’s quite possible. This submission was reorganized from 30 or 40 local patches, reordered
and grouped to make pull request easier to understand.
The most interesting part of the pull request is the last commit, of course.

**Comment by briot** [comment]
So did you finally succeed in applying all patches and merging ? I have more pull requests to submit, but until you can actually merge this one (and because all the others build on top of this one), there's no point doing so.

**Comment by anisimkov** [comment]
I can't apply it as is, it lead to regression in infosys.
I have to change infosys but don't have a time right now for it.
I was trying 2 times to begin infosys modifications, but was switched to another more important tasks.

**Comment by briot** [comment]
:-(
Out of curiosity, are the regressions only in the actual output (I know the type names might have changed and infosys testsuite is comparing the exact queries), or actual regressions/change of behavior ? On our side we haven't seen any change and queries still properly output the same results as before.

**Comment by anisimkov** [comment]
I'm not sure. Most probable only in output. To be sure I need to change all output and see diffs.

**Comment by anisimkov** [comment]
I can't understand for now what is the
-   <BTVC.FS> committed revision 13
+   <BTVC.FS> committed revision 3
And I cant continue this investigations for today.

**Comment by briot** [comment]
> I can't understand for now what is the
> 
> 	• <BTVC.FS> committed revision 13
> 	• <BTVC.FS> committed revision 3
> And I cant continue this investigations for today.

Sorry, no idea how this could be related to databases. Isn’t this some svn-related part
of infosys ?

**Comment by anisimkov** [comment]
I'll try to understand it tomorrow

**Comment by anisimkov** [comment]
The commit 38665327c68e7d9ae1a1a3b0772fc9ba3bac426a has regression because of miss test output fix. I can accept it merged only in case of clean regression. Or I can fix it myself and accept it cherry picked if you don't mind.

**Comment by briot** [comment]
> The commit 3866532 has regression because of miss test output fix. I can accept it merged only in case of clean regression. Or I can fix it myself and accept it cherry picked if you don't mind.

Dmitriy

I just reran the testuite locally on my machine, and I don’t see those regressions.

So indeed please go ahead if you can fix them. I do not mind if you cherry-pick
(though presumably the workflow should be something like:

     - create a branch locally on your machine
     - import my patches on that branch
     - add your patch
     - merge that branch into master with —no-ff

(that’s what I do locally now to maintain all the patches I want to submit). That means that tests need to be clean at the point of the merge, but it is acceptable if they are not in the middle of the branch. That helps keep the history readable too by keeping related patches on the same branch (that GPS will happily show you, too).

But again: do as you think best. It doesn’t matter to me if the patches are not submitted in my name. I really want them submitted, since those are complex patches, and I have a number of much simpler ones to submit later on.

You can also send the exact output you’re seeing, maybe that’ll ring a bell.

Thanks

Manu

**Comment by anisimkov** [comment]
The commit 3866532 was cherry-picked, fixed and approved.

**Comment by anisimkov** [comment]
<< It doesn’t matter to me if the patches are not submitted in my name.>> Your name is not touched, cherry-pick changing the commit id and github can't detect that patch was accepted.

I can't control so big modification at once, I can control it only incrementally.

**Comment by anisimkov** [comment]
in cd3ad81f2f5f9494a1d8850179a9b8b856f08eee
====== Building static tools ======
gprbuild  -p -m -j0 -XLIBRARY_TYPE=static -XGnatcoll_Build=Debug -XXMLADA_BUILD=static -q -Psrc/gnatcoll_tools
gnatcoll_db2ada-generate.adb:128:36: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:215:39: no selector "Get_Actual_Type" for private type "Field" defined at gnatcoll-sql-inspect.ads:57
gnatcoll_db2ada-generate.adb:530:07: no candidate interpretations match the actuals:
gnatcoll_db2ada-generate.adb:530:07: too many arguments in call to "Write_Schema"
gnatcoll_db2ada-generate.adb:531:13: "Connection" is undefined
gnatcoll_db2ada-generate.adb:531:33: unmatched actual "Puts" in call

**Comment by anisimkov** [comment]
Looks like "(Cast_To_Time): new function"  modification test is not time zone independent, I've got regression:

-SELECT ... CAST (mytable.ts1 AS DATE)='2017-01-01'
+SELECT ... CAST (mytable.ts1 AS DATE)='2016-12-31'

-SELECT ... CAST (mytable.ts1 AS TIME)='2017-01-01 01:00:54'
+SELECT ... CAST (mytable.ts1 AS TIME)='2016-12-31 14:00:54'

Strange difference +13 hours from my place (GMT+6), neither Paris nor NY as I can understand.

**Comment by briot** [comment]
> Looks like "(Cast_To_Time): new function" modification test is not time zone independent, I've got regression:
> 
> -SELECT ... CAST (mytable.ts1 AS DATE)='2017-01-01'
> +SELECT ... CAST (mytable.ts1 AS DATE)='2016-12-31'
> 
> -SELECT ... CAST (mytable.ts1 AS TIME)='2017-01-01 01:00:54'
> +SELECT ... CAST (mytable.ts1 AS TIME)='2016-12-31 14:00:54'
> 
> Strange difference +13 hours from my place (GMT+6), neither Paris nor NY as I can understand.

I think the testsuite is forcing a specific timezone:
testsuite/sql/__init__.py does
     os.environ[‘TZ’] = ‘NSZ-12’

For me, Cast_To_Time works better than it did before, but I might (again)
have got things wrong...

**Comment by anisimkov** [comment]
I do not see "NSZ-12" in whole gnatcoll

**Comment by anisimkov** [comment]
Maybe in next commit.. But I'm not going to accept all this commits at once because together they are broking another tools regression tests.

**Comment by briot** [comment]
> I do not see "NSZ-12" in whole gnatcoll

NZS-12

**Comment by anisimkov** [comment]
As a total for today, all except

Avoid duplicate with clauses in code generated from a database schema
(Cast_To_Time): new function
Improvements to GNATCOLL.SQL 

Accepted.

**Comment by anisimkov** [comment]
Ok I'll move the NZS-12 from last commit to appropriate one.

**Comment by anisimkov** [comment]
NZS-12 in 
```
--- a/testsuite/sql/__init__.py
+++ b/testsuite/sql/__init__.py
@@ -12,6 +12,10 @@ class Test(GNATCOLL_TestCase):
         if has_postgres:
             subprocess.call(['psql', '-f', 'sql/clear.sql', 'test'])
 
+        # Setup a timezone so that errors with times and dates are more likely
+        # to be seen
+        os.environ["TZ"] = "NZS-12"
+
```

does not help.

**Comment by briot** [comment]
It would really be more efficient for everyone if you could integrate all patches
altogether. It’s not like all commits taken separately in the history of gnatcoll
always had clean testsuite.
Let’s look at the result of the testsuite when all patches in this pull request
are integrated.

**Comment by briot** [comment]
So, where are we on this patch ? It is blocking a very large number of other patches I have to submit (but holding on to them since they are all based, at least in my repository, on this patch even when they might not depend on it directly).

**Comment by quinot** [comment]
Dmitriy is on vacation at the moment. Once he returns we'll review the remaining regressions.

**Comment by briot** [comment]
Should be closed, only integrated as part of #20

**Pull request closed without merging**
